-- 풀이 1
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS `TOTAL_STATUS`
  FROM USED_GOODS_BOARD AS B
  JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID = U.USER_ID
 WHERE STATUS = 'DONE' # WHERE절에 집계함수 또는 별칭으로 만든 항목 사용 불가
 GROUP BY U.USER_ID HAVING TOTAL_STATUS >= 700000
 ORDER BY TOTAL_STATUS

-- 풀이 2
SELECT U.USER_ID, U.NICKNAME, PRICE AS `TOTAL_SALES`
  FROM ( SELECT WRITER_ID, SUM(PRICE) AS PRICE
           FROM USED_GOODS_BOARD
          WHERE STATUS = 'DONE'
          GROUP BY WRITER_ID HAVING PRICE >= 700000
       ) AS B
  JOIN USED_GOODS_USER AS U
    ON U.USER_ID = B.WRITER_ID
 ORDER BY TOTAL_SALES